version: '3.6'
services:
  influxdb:
    image: influxdb:1.8-alpine
    restart: always
    env_file: configuration.env
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb

  chronograf:
    image: chronograf:1.8-alpine
    restart: always
    volumes:
      - chronograf_data:/var/lib/chronograf
    depends_on:
      - influxdb
    ports:
      - '8888:8888'
    env_file: configuration.env
  
  grafana:
    image: grafana/grafana:7.0.0
    restart: always
    depends_on:
      - influxdb
    env_file: configuration.env
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/

volumes:
  grafana_data: 
  influxdb_data: 
  chronograf_data: